### ISSUE TITLE
**Mettre en place l'intégration continue:**

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/GL51-projet#1]
mettre en place travis CI
poster ici : le lien vers votre travis et votre repository

**Comment by science162** [comment]
Pair : Mouaffo Kamga Régis Albert --  Kameni Tuete Vanessa Orneila

https://travis-ci.com/science162/GL51-projet/builds/106310256

**Comment by dbissari** [comment]
Pair : Déromba Serge BISSARI & Arona Gueye

https://travis-ci.com/dbissari/GL51_Project/builds/106311303

**Comment by XinyuSHAN** [comment]
Pair: Linzi MA & Xinyu SHAN
https://travis-ci.com/XinyuSHAN/GL51_project/builds/106768316

**Comment by YannPoncet** [comment]
Groupe : Boris BROGLE - Yann PONCET - Rodolphe PONTHON
https://travis-ci.org/YannPoncet/Project-GL51/builds/515155863

**Comment by martin-plessy** [comment]
Faraj Al Btadini – Martin Plessy : https://github.com/martin-utbm/gl51-micronaut

**Comment by ThomasGubien** [comment]
Groupe: Éloïse GRILLET - Thomas GUBIEN
https://travis-ci.org/ThomasGubien/projet-gl51/builds/515827147

**Comment by aitianshi** [comment]
**Groupe :** Alban PEZZOLI - Etienne FILHOL
**Travis :** https://travis-ci.com/aitianshi/gl51/builds/107336667
**Repository :** https://github.com/aitianshi/gl51

**Comment by balmajoe** [comment]
Groupe : Linda JEMMI -Josue BALMA
[Travis](https://travis-ci.org/balmajoe/gl51_project/builds/517884051)

**Comment by zikas96** [comment]
https://travis-ci.com/zikas96/GL51-TP2/builds/107826156

**Comment by Czq96** [comment]
Groupe: Ying WU - Zhuoqi CHEN
Travis:  https://travis-ci.org/Czq96/GL51/builds/513613816

**Comment by blomios** [comment]
Groupe: Bouteiller Anthony, Luc Heydel
Travis: https://travis-ci.org/blomios/gl51/builds/518417711
GitHub: https://github.com/blomios/gl51

**Comment by shuxuzhipeng** [comment]
Groupe:Zhipeng XU,Tan ZHANG
Travis: https://travis-ci.com/shuxuzhipeng/GL51_PROJECT/builds/107972607

**Comment by CCHENJiajie** [comment]
Groupe: Jiajie CHEN - Sicong HUANG
Travis: https://travis-ci.com/CCHENJiajie/GL51_project/builds/107983639

**Comment by Tibdub** [comment]
Groupe DUBOIS Thibault - William Djousse
https://travis-ci.org/wdjousse/GLprojet/builds/518925062

**Comment by Integrale18** [comment]
GROUPE : LOHO KOASSIVI
https://travis-ci.com/Integrale18/micronauteproject/builds/108020299

**Comment by LPA2-Automne2016** [comment]
OK
