### ISSUE TITLE
Créer une liste de produit:

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/GL51-projet#2]
créer une liste de produits a partir de la base de données

liste des tests possibles:

* empty storage returns empty list
* adding a product returns the product in the list
* adding a product will generate a new id
* deleting a product will remove it from the list
* modifying a product will change it in the list
* getting a product by its id will throw a NotExistingProductException if it does not exits
* getting a product by its id will return it if it does exist

**Comment by LPA2-Automne2016** [comment]
créer les tests listés ci dessus, pousser le code dans une nouvelle branche de github.
ouvrir une merge request et lister l'url de la pull request

ATTENTION   je veux voir dans la pull request le resultat du CI !

**Comment by aitianshi** [comment]
**Pair :** Alban PEZZOLI - Etienne FILHOL
**Pull Request :** https://github.com/aitianshi/gl51/pull/1

**Comment by dbissari** [comment]
**Pair :** Déromba Serge Bissari & Arona Gueye
**Pull Request :** https://github.com/dbissari/GL51_Project/pull/1

**Comment by YannPoncet** [comment]
**Group:** BROGLE Boris - PONCET Yann - PONTHON Rodolphe
**Pull Request:** https://github.com/YannPoncet/Project-GL51/pull/1

**Comment by lheydel** [comment]
**Pair:** Anthony BOUTEILLER - Luc HEYDEL
**Pull Request:** [blomios/GL51-Project#1](https://github.com/blomios/GL51-Project/pull/1)

**Comment by vokt** [comment]
**Pair :** Vanessa Kameni - Albert Mouaffo
**Pull request :** https://github.com/science162/GL51-projet/pull/2

**Comment by martin-plessy** [comment]
Faraj Al Btadini – Martin Plessy : https://github.com/martin-utbm/gl51-micronaut/pull/1

**Comment by ThomasGubien** [comment]
Pair: Grillet Eloïse - Gubien Thomas
Pull request: https://github.com/ThomasGubien/projet-gl51/pull/1

**Comment by balmajoe** [comment]
group: Balma josué - Jemni linda
lien:[pull request](https://github.com/balmajoe/gl51_project/pull/1)

**Comment by Tibdub** [comment]
Groupe DUBOIS Thibault - DJOUSSE William
https://github.com/Tibdub/GL51-projet/pull/2
(j'ai été un peu vite dans la manip et j'ai merge la branche..)

**Comment by Czq96** [comment]
groupe: CHEN Zhuoqi - WU Ying
https://github.com/Czq96/GL51/pull/1

**Comment by shuxuzhipeng** [comment]
groupe: XU Zhipeng ZHANG Tan
https://github.com/shuxuzhipeng/GL51-td3/pull/1

**Comment by CCHENJiajie** [comment]
group: CHEN Jiajie  -  HUANG Sicong
Pull request: https://github.com/CCHENJiajie/GL51_td3/pull/1

**Comment by zikas96** [comment]
pair: NAJI Zakaria
Pull request :  https://github.com/zikas96/GL51-TP2/pull/1

**Comment by zikas96** [comment]
pair : NAJI Zakaria
Pull request ; https://github.com/zikas96/GL51-TP2/pull/1

**Comment by XinyuSHAN** [comment]
**Pair** : Xinyu SHAN - Linzi MA
Pull Request : [XinyuSHAN/GL51_project#1](https://github.com/XinyuSHAN/GL51_project/pull/1)

**Comment by Integrale18** [comment]
LOHO KOASSIVI

pull request : https://github.com/Integrale18/micronauteproject/pull/1

**Comment by LPA2-Automne2016** [comment]
Bravo à tous, j'ai commenté chacune de vos MR, en y glissant un peu de doc lorsque c'est approprié.
prenez le temps de lire cette doc, cela vous permettra de progresser
