### ISSUE TITLE
Mettre en place le controlleur de la liste des produits

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/GL51-projet#5]
écrire les tests unitaires du controlleur pour tester le fonctionnement du CRUD:
démarche idem à celle du inmemorystore.

tester la fonctionnalité de Create/Read/Update/Delete

remonter le code dans une branche à part et mettre ici l'url de la Pull request

**Comment by dbissari** [comment]
**Pair :** Déromba Serge Bissari & Arona Gueye
**Pull Request :** https://github.com/dbissari/GL51_Project/pull/3

**Comment by Integrale18** [comment]
LOHO KOASSIVI

PR : https://github.com/Integrale18/micronauteproject/pull/5

**Comment by ThomasGubien** [comment]
Pair: Grillet Éloïse & Gubien Thomas
Pull Request: https://github.com/ThomasGubien/projet-gl51/pull/3

**Comment by balmajoe** [comment]
Pair: Balma Josué & Linda Jemni
Link:[contoller](https://github.com/balmajoe/gl51_project/pull/2)

**Comment by ThomasGubien** [comment]
Pair: Grillet Eloïse & Gubien Thomas
Pull Request: https://github.com/ThomasGubien/projet-gl51/pull/4

**Comment by lheydel** [comment]
**Pair**: Anthony Bouteiller & Luc Heydel
**Pull Request**: [blomios/GL51-Project#3](https://github.com/blomios/GL51-Project/pull/3)

**Comment by Czq96** [comment]
Pair: Ying WU & Zhuoqi CHEN
https://github.com/Czq96/GL51/pull/2

**Comment by YannPoncet** [comment]
**Group**: Boris BROGLE - Yann PONCET - Rodolphe PONTHON
**Pull Request**: https://github.com/YannPoncet/Project-GL51/pull/2

**Comment by aitianshi** [comment]
Group: Alban Pezzoli & Etienne Filhol
Pull Request : [Click here](https://github.com/aitianshi/gl51/pull/5)

**Comment by vokt** [comment]
Group : kameni vanessa & mouafo albert
pull request : https://github.com/science162/GL51-projet/pull/3

**Comment by LPA2-Automne2016** [comment]
Bon travail pour ceux qui ont répondu.
