### ISSUE TITLE
Terminer l'intégration de coverall

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/GL51-projet#8]
Rendre ici l'url de la pull request finale, avec :
travis qui fonctionne
codefactor avec un A
coveralls avec une couverture à 80 % minimum

**Comment by ThomasGubien** [comment]
Pair: Griller Eloïse & Gubien Thomas
Merge Request: https://github.com/ThomasGubien/projet-gl51/pull/5

**Comment by dbissari** [comment]
**Pair :** Déromba Serge Bissari & Arona Gueye
**Pull Request :** https://github.com/dbissari/GL51_Project/pull/6

**Comment by aitianshi** [comment]
**Group :** Alban Pezzoli & Etienne Filhol
**Pull Request :** [Click Here](https://github.com/aitianshi/gl51/pull/7)

**Comment by YannPoncet** [comment]
**Group**: Boris BROGLE - Yann PONCET - Rodolphe PONTHON
**Pull Request**: https://github.com/YannPoncet/Project-GL51/pull/3

**Comment by Czq96** [comment]
pair: Ying WU    &   Zhuoqi CHEN
https://github.com/Czq96/GL51/pull/3

**Comment by vokt** [comment]
Pair : Kameni Vanessa & Mouafo Albert 
Pull request : https://github.com/science162/GL51-projet/pull/5

**Comment by martin-plessy** [comment]
Faraj Al Btadini – Martin Plessy : https://github.com/martin-utbm/gl51-micronaut/pull/4

**Comment by Tibdub** [comment]
Dubois Thibault - William Djousse : https://github.com/Tibdub/GL51-projet/pull/4

**Comment by shuxuzhipeng** [comment]
Zhipeng Xu-Tan ZHANG:https://github.com/shuxuzhipeng/gl51td3/pull/3

**Comment by Integrale18** [comment]
LOHO KOASSIVI
https://github.com/Integrale18/micronauteproject/pull/7

**Comment by CCHENJiajie** [comment]
Group : Jiajie CHEN - Sicong HUANG
Pull request : https://github.com/CCHENJiajie/GL51td/pull/1

**Comment by lheydel** [comment]
**Group** : Anthony BOUTEILLER - Luc HEYDEL
**Pull Request** : [Click Here](https://github.com/blomios/GL51-Project/pull/3/#issue-281759193)

**Comment by XinyuSHAN** [comment]
Group : Xinyu SHAN - Linzi MA
 Pull Request: https://github.com/XinyuSHAN/GL51_project/pull/6

**Comment by zikas96** [comment]
group : NAJI-Zakaria
Pull request : https://github.com/zikas96/GL51-TP2/pull/3

**Comment by balmajoe** [comment]
group: balma josué - jemni linda
[pull request](https://github.com/balmajoe/gl51_project/pull/3)
